### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by brent185** [elchininet/isometric#104]
import (no other isometric specific declarations or code) causes this build error: 

Error: node_modules/@elchininet/isometric/index.d.ts:195:9 - error TS2380: The return type of a 'get' accessor must be assignable to its 'set' accessor type
  Type 'undefined' is not assignable to type 'Texture'.

195     get texture(): Texture | undefined;
            ~~~~~~~

**Comment by elchininet** [comment]
Hi @brent185,
Could you provide a link to the repository in which you are having this build issue?
Regards

**Comment by elchininet** [comment]
Hi @brent185,
Looking at the last part of the error I got from which place it was coming.
I removed the `undefined` type from the getter even if it is possible to return an `undefined` value becase it doesn‘t clash with any other functionality.
Try the version [3.7.2](https://www.npmjs.com/package/@elchininet/isometric/v/3.7.2) of the package, the issue should be solved there.
Regards
