### ISSUE TITLE
Unable to Place SVG Image on a Rectangle

### ISSUE THREAD

**Issue by rahulnayanegali** [elchininet/isometric#109]
I was attempting to use the isometric library to create an isometric design with an SVG image on a rectangle. However, I couldn't find any documentation or examples on how to achieve this.

I tried setting the **texture** property of the **IsometricRectangle** object to the SVG image URL, but it didn't work. The image didn't show up on the rectangle.

Could you please provide some guidance or examples on how to place an SVG image on a rectangle using the isometric library? It would be very helpful if there was some documentation or a demo that explains this feature.

Thank you for your help!

**Comment by elchininet** [comment]
Hi @rahulnayanegali,
The last example of [the demo page](https://elchininet.github.io/isometric/) shows you how to do that. One of the elements is an `IsometricRectangle`.
Regards

**Comment by elchininet** [comment]
Hi @rahulnayanegali,
Do you know already how to work with textures?
Regards

**Comment by elchininet** [comment]
Hi @rahulnayanegali,
It seems that you already solved your doubt.
Closing this issue.
Regards
