### ISSUE TITLE
Animating width and height at the same time.

### ISSUE THREAD

**Issue by joelburget** [elchininet/isometric#215]
I'd like to be able to animate both properties on the same rectangle, but it looks like only one has an effect. https://codepen.io/joelburget/pen/PwYpMVB is a very simple example.

Also, if I change `values: [1, 0.1, 1]` to `values: [1, 0, 1]` the animation goes away entirely.

**Comment by elchininet** [comment]
>I'd like to be able to animate both properties on the same rectangle, but it looks like only one has an effect.

That is a limitation of some animating properties, you need to check in the documentation of each class, the section for `addAnimation`. This is the one relative to `IsometricRectangle`:

---

These are the properties that can be animated (property `property`)

* fillColor
* fillOpacity
* strokeColor
* strokeOpacity
* strokeWidth
* right\*
* left\*
* top\*
* width\*
* height\*

>\* At the moment, it is not possible to animate more than one of these properties at the same time. If you do it, only the last one will be applied.

---

>Also, if I change values: [1, 0.1, 1] to values: [1, 0, 1] the animation goes away entirely.

I'll check it.

**Comment by elchininet** [comment]
Hi @joelburget,
The issue with the `0` values has been fixes in the version [3.10.1](https://www.npmjs.com/package/@elchininet/isometric/v/3.10.1).
The issue related to only accepting the last property is expected as the aforementioned limitation.
Regards
