### ISSUE TITLE
Support CSS Classes?

### ISSUE THREAD

**Issue by joelburget** [elchininet/isometric#216]
Instead of directly specifying properties like `fillColor`, I'd like to be able to use classes.

Why? Primarily because I want to support dark mode. It's much easier to apply a class to an element and allow it to change automatically based on `@media (prefers-color-scheme: dark) { ... }` rather than handling the event `window.matchMedia('(prefers-color-scheme: dark)').addEventListener('change', event => { ... })`.

**Comment by elchininet** [comment]
@joelburget,
Let's discuss it in the PR.

**Comment by elchininet** [comment]
@joelburget,
The version [v3.11.0](https://www.npmjs.com/package/@elchininet/isometric/v/3.11.0) has been released with this change.
Regards
