### ISSUE TITLE
Textures

### ISSUE THREAD

**Issue by WildlandHerald** [elchininet/isometric#52]
Hello! This project looks sick! But is it possible to draw any textures (like images) on the isometric surfaces at this point?

**Comment by elchininet** [comment]
Hi @WildlandHerald, it is not possible to add textures at this point, but it is an interesting feature to take into account. Meanwhile, you can check [isometric-css](https://github.com/elchininet/isometric-css), it is not the same as this library but maybe you will find it interesting.
Regards

**Comment by WildlandHerald** [comment]
@elchininet Thanks for the answer! Nice to know you consider this feature, will also check out isometric-css, seems cool at first glance.

**Comment by elchininet** [comment]
Hi @WildlandHerald, you can find initial support for textures in [version 3.1.0](https://www.npmjs.com/package/@elchininet/isometric/v/3.1.0) of the package. 
For more info, you can check [this pull request](https://github.com/elchininet/isometric/pull/55) or [demo 6](https://elchininet.github.io/isometric/#demo6) on the demo page.

Regards and thanks for using the library 👍
