### ISSUE TITLE
Can you add a drag-and-drop demo example?

### ISSUE THREAD

**Issue by flashoop** [elchininet/isometric#74]
I want to understand how each Block drags and drops

**Comment by elchininet** [comment]
Hi @flashoop,
Unfortunately the code involved to perform a drag and drop would be too long for an example code in the demo that it is intended to be short and just show the capabilities of the API. But I can make an example for you in CodePen with a simple drag and drop of a shape.
Regards.

**Comment by elchininet** [comment]
Hi @flashoop,
Here you go: https://codepen.io/elchininet/pen/PoQypZQ
You can adapt it to your needs.
Regards.

**Comment by elchininet** [comment]
Hi @flashoop, an update. The version 3.5.0 of the library supports automatic drag and drop. I updated the previous Codepen to use this new functionality. You can also consult [the demo 6](https://elchininet.github.io/isometric/#demo6).
Hope you find it useful.
Regards.

**Comment by flashoop** [comment]
thanks for you hard work
