### ISSUE TITLE
about how to connnet two boxes with line?

### ISSUE THREAD

**Issue by flashoop** [elchininet/isometric#82]
Is there a way to connect two boxes, which is to connect two boxes through a straight line, and these two boxes can be grouped and dragged at the same time

Is there any demo to test it ?

**Comment by elchininet** [comment]
Hey @flashoop, the `IsometricGroup` class is a container in which you can add any `IsometricElement` (except `IsometricCanvas`). So you can add any element to a group, including other groups. Later you can set up the drag property in a group to be able to drag and drop it.

Here you have a small example: https://jsfiddle.net/elchininet/6ht8enbx/

Regards

>Note: I have enabled the discussions section, if you have a question or you want to discuss something it is better in that section than in the issues one.
