### ISSUE TITLE
IsometricText?

### ISSUE THREAD

**Issue by jameslounds** [elchininet/isometric#90]
Is there a way to write text using this library?

I could use pre-generated text images for certain faces, but this seems unwieldily.

**Comment by elchininet** [comment]
Hi @jameslounds,
I have a work-in-progress local branch to bring this feature but it is not as easy as it seems. It is hard to set the coordinates of transformed text elements in SVGs.
If I make some progress on it and I can release this feature, I‘ll let you know.
Regards

**Comment by elchininet** [comment]
Hi @jameslounds,

The `IsometricText` class has been added in the [version 3.7.0 of the package](https://www.npmjs.com/package/@elchininet/isometric/v/3.7.0). You can check [the documentation about its usage](https://github.com/elchininet/isometric#class-isometrictext), or consult the third example on the [demo page](https://elchininet.github.io/isometric/).

I hope it satisfies your needs.

Regards!
